CC = icpc 
OPT = -fast -xHost -restrict -no-prec-div
CFLAGS = -std=c++14 $(OPT)
MKLROOT = /afs/crc.nd.edu/x86_64_linux/intel/15.0/mkl
LDLIBS = -lrt -Wl,--start-group $(MKLROOT)/lib/intel64/libmkl_intel_lp64.a $(MKLROOT)/lib/intel64/libmkl_sequential.a $(MKLROOT)/lib/intel64/libmkl_core.a -Wl,--end-group -lpthread -lm

targets = test
objects = test.o

.PHONY : default
default : all

.PHONY : all
all : clean $(targets)

test : test.o
	$(CC) -o $@ $^ $(LDLIBS)

%.o : %.cpp
	$(CC) -c $(CFLAGS) $<

.PHONY : clean
clean:
	rm -f $(targets) $(objects) *.stdout
